version: '3.7'

services: 
  db:
    container_name: groupr-mysql
    image: mysql:latest
    volumes:
      - "./data/mysql:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz@WSX